# 只支持 16:9!!! 
# FHD: 1920 * 1080: 1
# QHD: 2560 * 1440: 1.333
# UHD: 3840 * 2160: 2
# 只与游戏内设置的分辨率有关
SCALE_FACTOR: 1

tech:
# 技术中心
  - [沙暴垂直补偿器, -1]
work:
# 工作台
  - [9x39mm SP6, -1]
medical:
# 制药台
  - [OE2战斗兴奋剂, -1]
armor:
# 防具台
  - [精英防弹背心, -1]

# 高级设置
TESSERACT_PATH: C:\Program Files\Tesseract-OCR\tesseract.exe
background_mode: false
debug_mode: true
